### ISSUE TITLE
Preserving this project's code history

### ISSUE THREAD

**Issue by ryandesign** [FredHucht/pstree#1]
Since you managed the source code of this project with RCS since 1994, I wonder why you did not import that history into GitHub. Preserving history is valuable. RCS can be converted to CVS which can be converted to Subversion which can be converted to Git, or there may be a more direct route.

**Comment by FredHucht** [comment]
That's true, so I merged the RCS history into GitHub using `rcs-fast-export.rb`. Unfortunately, I had to change the default branch for that, such that forks and clones might not work anymore. Simply re-[fork|clone].

GitHubs solution read:

The default branch has been renamed!
rcs_history is now named main
If you have a local clone, you can update it by running the following commands.
git branch -m rcs_history main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
